/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Lead = IDL.Record({
  'monthlyBudget' : IDL.Text,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitLead' : IDL.Func([Lead], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'monthlyBudget' : IDL.Text,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitLead' : IDL.Func([Lead], [], []),
  });
};

export const init = ({ IDL }) => { return []; };